version: '3.7'

services:
  # Zookeeper is a requirement for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.15
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Kafka message broker
  kafka:
    image: confluentinc/cp-kafka:7.2.15
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # MySQL Database for generating logs
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
      - mysql-logs:/var/log/mysql # Shared volume for logs

  rsyslog:
    image: rsyslog/rsyslog:2025-04
    container_name: rsyslog
    depends_on:
      - mysql
      - kafka
    volumes:
      - ./config/rsyslog:/etc/rsyslog.d
      - mysql-logs:/var/log/mysql:ro # Mount logs as read-only

  
  # PostgreSQL Database to store the logs
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mysqllogs
    ports:
      - "5432:5432"


  consumer:
    image: consumer:0.1.0
    container_name: consumer
    depends_on:
      - kafka
      - postgres

volumes:
  mysql-logs: # Define the shared volume