# deploy.yml
---
- name: Deploy Logging Pipeline
  hosts: all
  become: yes
  gather_facts: yes  
  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Include docker setup role
      include_role:
        name: docker

    - name: Include pipeline deployment role
      include_role:
        name: deploy_pipeline
