name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        cd consumer
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run unit tests
      run: |
        cd consumer
        python -m pytest tests/ -v --cov=. --cov-report=xml

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./consumer/coverage.xml

    - name: Lint Python code
      run: |
        pip install flake8 black
        cd consumer
        black --check .
        flake8 .

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build consumer image
      run: |
        cd consumer
        docker build -t consumer:latest .

    - name: Run container tests
      run: |
        cd consumer
        docker run --rm consumer:latest python -m pytest tests/ -v

    - name: Save Docker image
      run: |
        cd consumer
        docker save consumer:latest -o consumer-image.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: consumer-image
        path: consumer/consumer-image.tar